version: '3.8'

services:
  acestep-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./models:/app/models
    environment:
      - DEFAULT_CHECKPOINT_PATH=/app/models/checkpoint
      - DEFAULT_DEVICE_ID=0
      - DEFAULT_BF16=true
      - DEFAULT_TORCH_COMPILE=false
      - OUTPUT_DIR=/app/outputs
      - PORT=8000
      - LOG_LEVEL=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  models:
  outputs:

